### ISSUE TITLE
doc : Bellecombe.zip not avalable

### ISSUE THREAD

**Issue by ElCep** [OceletTeam/ocelet#36]
Dear dev Team, 
An easy issue ! On the website, I was reading the documentation section. The first example "bellecombe" is not available. In both English and French part. 
```
Bolt - Fatal error.
*Class: Symfony\Component\HttpKernel\Exception\NotFoundHttpException
*Message: The page could not be found, and there is no 'notfound' set in 'config.yml'. Sorry about that.
*Code: 0
```
Thank you, 
E.

**Comment by padeg** [comment]
Fixed it, sorry about that.
Thank you Etienne.
